version: "3.8"
services:

    chat-server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: app-server
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        networks:
            - chatting
        ports:
            - 50051:50051
        container_name: app-server

    chat-client:
        build:
            context: ./client/GrpcClient
            dockerfile: GrpcClient/Dockerfile
        image: app-client
        networks:
            - chatting
        container_name: app-client

networks:
    chatting:
        name: chatting_network