# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_app_pb2 as chat__app__pb2


class ChatAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receiveMessages = channel.unary_stream(
                '/chat.ChatApp/receiveMessages',
                request_serializer=chat__app__pb2.StartRequest.SerializeToString,
                response_deserializer=chat__app__pb2.ChatMessage.FromString,
                )


class ChatAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def receiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.receiveMessages,
                    request_deserializer=chat__app__pb2.StartRequest.FromString,
                    response_serializer=chat__app__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.ChatApp/receiveMessages',
            chat__app__pb2.StartRequest.SerializeToString,
            chat__app__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
