# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat_app.proto',
  package='chat',
  syntax='proto3',
  serialized_options=b'\252\002\nGrpcClient',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63hat_app.proto\x12\x04\x63hat\"\x1c\n\x0cStartRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x0b\x43hatMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t2G\n\x07\x43hatApp\x12<\n\x0freceiveMessages\x12\x12.chat.StartRequest\x1a\x11.chat.ChatMessage\"\x00\x30\x01\x42\r\xaa\x02\nGrpcClientb\x06proto3'
)




_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='chat.StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chat.StartRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='chat.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='chat.ChatMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'chat_app_pb2'
  # @@protoc_insertion_point(class_scope:chat.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'chat_app_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)


DESCRIPTOR._options = None

_CHATAPP = _descriptor.ServiceDescriptor(
  name='ChatApp',
  full_name='chat.ChatApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=82,
  serialized_end=153,
  methods=[
  _descriptor.MethodDescriptor(
    name='receiveMessages',
    full_name='chat.ChatApp.receiveMessages',
    index=0,
    containing_service=None,
    input_type=_STARTREQUEST,
    output_type=_CHATMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATAPP)

DESCRIPTOR.services_by_name['ChatApp'] = _CHATAPP

# @@protoc_insertion_point(module_scope)
